@BASE_URL= http://localhost:8080/api/almacenes

###
GET {{BASE_URL}}?size=20
###
GET {{BASE_URL}}/5
###
POST {{BASE_URL}} HTTP/1.1
content-type: application/json

{
    "departamento": "Lima",
    "provincia": "Lima",
    "distrito": "Lurigancho Chosica",
    "nombre": "Almacen Chosica",
    "latitud": "-12.0931",
    "longitud": "-77.0465",
    "foto": "http://example.com/foto_almacen_chosica.jpg"
}
###
PUT {{BASE_URL}}/12 HTTP/1.1
content-type: application/json

{
    "departamento": "Cajamarca",
    "provincia": "Cajamarca",
    "distrito": "Ñañu",
    "nombre": "Almacen Ñañu",
    "latitud": "-12.0931",
    "longitud": "-89.0465",
    "foto": "https://example.com/foto_almacen_ñañu.jpg"
}
###
PATCH {{BASE_URL}}/dar-baja/5 HTTP/1.1